# Generated by Django 4.2.1 on 2023-06-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_list',
            old_name='price',
            new_name='bid',
        ),
    ]
