# Generated by Django 4.2.1 on 2023-06-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_list_bid_alter_auction_list_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_list',
            name='bid',
        ),
    ]
